### ISSUE TITLE
<~> operator not found

### ISSUE THREAD

**Issue by sbrother** [expede/quark#15]
On Quark 2.3.0, Elixir 1.5.1, the reversed composition operator (<~>) mentioned the documentation does not seem to exist. Is this a version issue? 

```
iex(3)> use Quark
Quark.Pointfree
iex(4)> f = &(&1)
#Function<6.99386804/1 in :erl_eval.expr/5>
iex(5)> g = &(&1)
#Function<6.99386804/1 in :erl_eval.expr/5>
iex(6)> f <|> g
#Function<1.107413978/1 in Quark.Compose.compose/2>
iex(7)> f <~> g
** (CompileError) iex:7: undefined function <~>/2
```

**Comment by OvermindDL1** [comment]
Should probably be stated in the docs but `use Quark` only brings in a few things, to get something like `<~>` you also need to `import Quark.Compose`.  ^.^

**Comment by sbrother** [comment]
Oh! Thanks :)
