### ISSUE TITLE
Curried functions don't work when they are called directly with arguments.

### ISSUE THREAD

**Issue by AionDev** [expede/quark#17]
Just starting out with functional concepts in elixir. I've taken this form the docs.
```
defmodule Foo do
  use Quark.Curry

  defcurry(div(a, b), do: a / b)
end

defmodule Bar do
  def test do
    # this doesn't work
    # Foo.div(10, 5)
    # |> IO.inspect()

    # this also doesn't work - is the error below.
    Foo.div(10).(5)
    |> IO.inspect()

    # this works! produces 5 as expected.
    # Foo.div().(10).(2)
    # |> IO.inspect()
  end
end

Bar.test()
```
Error: 
```

** (UndefinedFunctionError) function Foo.div/1 is undefined or private. Did you mean one of:

      * div/0

    Foo.div(10)
    repl/test.exs:13: Bar.test/0
    (elixir) lib/code.ex:677: Code.require_file/2
    (mix) lib/mix/tasks/run.ex:136: Mix.Tasks.Run.run/5
    (mix) lib/mix/tasks/run.ex:76: Mix.Tasks.Run.run/1
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:80: Mix.CLI.run_task/2
    (elixir) lib/code.ex:677: Code.require_file/2
```
Am i doing something wrong here? Thanks 😄

**Comment by OvermindDL1** [comment]
> Bar.test()

You just need to add a dot between `test` and `()` like:  `Bar.test.()`

That is what currying means.  :-)

**Comment by AionDev** [comment]
@ OvermindDL1 
I did what you said. Still the same error.

![documentation is broken or this is a bug](https://user-images.githubusercontent.com/20288140/37150734-7c2b2794-22db-11e8-8956-2261ba1bbf9e.png)

**Comment by OvermindDL1** [comment]
Hmm, I'm thinking that is more of a 'traditional call example' then the actual API, because it definitely does not expose a non-0-arg version of the function as you can see at:  https://github.com/expede/quark/blob/master/lib/quark/curry.ex#L92-L98

**Comment by emoragaf** [comment]
I think that in the example the `div(10, 2)` is calling `Kernel.div/2` and not `Foo.div`

`div.(10).(2)` is just syntactic sugar of your successful test `div().(10).(2)`
